import type { ModelReview } from './types';

export const MODEL_REVIEWS: ModelReview[] = [
  {
    id: 'kristina',
    name: 'Kristina',
    meta: 'Switched agencies',
    rating: 5,
    featured: true,
    tags: ['Manager', 'Support'],
    initials: 'K',
    avatarHue: 195,
    text: 'I want to say a word about our manager Yulia — such a responsive, sweet and kind person, takes her work seriously, a true professional! I had a bad experience with another agency at first, I won’t go into details. Yulia helped me solve the problems that came up, and we handled them thanks to her. She found me a new team, and with them I’m starting a new chapter of my life — the team is really great ❤️ Thank you, Yulia, for your help and support! All the best 🥰🙏',
  },
  {
    id: 'alina',
    name: 'Alina',
    meta: 'Starting with the team',
    rating: 5,
    tags: ['Onboarding', 'Support'],
    initials: 'A',
    avatarHue: 330,
    text: 'Hi! Everything’s great — they helped with lighting and an apartment for my first content plan. The team helps with any difficulties: if something doesn’t work out, they find an alternative or explain how to do it differently. So far so good, even if it was hard at first — you just need to get used to it and find your rhythm ♥️♥️',
  },
  {
    id: 'karina',
    name: 'Karina',
    meta: '2 weeks with OFM',
    rating: 5,
    tags: ['Advance', 'Content'],
    initials: 'K',
    avatarHue: 25,
    text: 'So glad I found your agency 🌸 You paid an advance already after my first content! You help create quality content, polite and attentive 💖 We’ve been working together for two weeks — and this is just the beginning! With your agency I see a future and real success ahead, which we’ll achieve together.',
  },
  {
    id: 'veronika',
    name: 'Veronika',
    meta: 'Launched in days',
    rating: 4,
    tags: ['Fast start', 'Honest'],
    initials: 'V',
    avatarHue: 280,
    text: 'The girls are so kind — they’ll listen and find the best option for you; the main thing is not to be shy and to talk about all your boundaries and details. They found a team quickly, within a few days we’d already started working — and the account already has good balances! Tip: double-check any detail so you don’t end up in an awkward spot later. Getting into the swing of it was tricky at first, but it all comes with experience 🥺 Honestly, I don’t regret it one bit.',
  },
  {
    id: 'oksana',
    name: 'Oksana',
    meta: 'Professional approach',
    rating: 5,
    tags: ['Professionalism'],
    initials: 'O',
    avatarHue: 160,
    text: 'Sincerely grateful for the collaboration. Genuinely impressed by the work and professionalism of the agency’s staff. They got to work fast — I was pleasantly surprised by how responsibly and thoroughly they did everything within their power, and even more. They work professionally at every stage.',
  },
  {
    id: 'natalia',
    name: 'Natalia',
    meta: 'Open from day one',
    rating: 5,
    tags: ['Trust', 'Support'],
    initials: 'N',
    avatarHue: 210,
    text: 'Right from the start of working together I felt trust in the staff — they gave clear, honest information about the collaboration and the earnings. After that I worked with the team: they support me, help me, give good advice. It’s a real pleasure to work with people who create such a good atmosphere even online.',
  },
];
