import type { ModelReview } from './types';

export const MODEL_REVIEWS: ModelReview[] = [
  {
    id: 'anna',
    name: 'Anna',
    meta: 'Creator · 5 mo. with OFM',
    dateLabel: '2 months ago',
    rating: 5,
    featured: true,
    tags: ['Chatting', 'Revenue growth'],
    helpfulCount: 14,
    text: 'Honestly: before OFM I was handling DMs myself until late at night and burned out by month two. Once I joined, managers took over chatting and I could focus on shoots and my content plan. Over five months my gross revenue grew roughly 4x — not saying everyone will get the same, this is my case. Downside: the first week was all setup, lots of questions on Telegram.',
    resultNote: 'Currently around ~$26–30k/mo (varies)',
    initials: 'A',
    avatarHue: 330,
    agencyReply: {
      text: 'Anna, thank you for the honest review — we passed your feedback to the chat team. Glad the process is working for you now. We\'re always here.',
      dateLabel: '2 months ago · OFM reply',
    },
  },
  {
    id: 'daria',
    name: 'Daria',
    meta: 'Creator · 3 mo. with OFM',
    dateLabel: '3 weeks ago',
    rating: 4,
    tags: ['Chatting', 'Onboarding'],
    helpfulCount: 8,
    text: 'Gave it a 4, not 5, on purpose. Solid start, manager is reasonable. In the first two weeks the tone in messages felt too salesy — I asked them to soften it and they fixed it within a couple of days. Comfortable now. Marketing is still ramping up, numbers are climbing but not at the finish line yet.',
    resultNote: 'Around $11–13k/mo at the moment',
    initials: 'D',
    avatarHue: 25,
    agencyReply: {
      text: 'Daria, noted. We adjusted the DM tone to match your style. If anything comes up — message your manager directly, that\'s a normal part of the process.',
      dateLabel: '2 weeks ago · OFM reply',
    },
  },
  {
    id: 'sofia',
    name: 'Sofia',
    meta: 'Creator · 6 mo. with OFM',
    dateLabel: '1 month ago',
    rating: 5,
    tags: ['Starting from scratch', 'Marketing'],
    helpfulCount: 21,
    text: 'I came in almost from zero, worried about verification and "what if it doesn\'t work out." They walked me through step by step with no pressure to sign on the day I applied. Reddit + Twitter actually brought traffic, and I wasn\'t handling chats at night — slept properly for the first time in ages. After six months the numbers are completely different for me; before it was around $3k.',
    resultNote: 'Personal experience: was ~$3k → now ~$28–34k/mo',
    initials: 'S',
    avatarHue: 195,
  },
  {
    id: 'victoria',
    name: 'Victoria',
    meta: 'Creator · 8 mo. with OFM',
    dateLabel: '6 weeks ago',
    rating: 5,
    tags: ['Brand', 'Content'],
    text: 'What mattered to me wasn\'t just running a page but building an image. I\'d tried two other teams before — chaos. Here there\'s a plan, the manager replies on Telegram, weekly number reports. Not flawless, but finally feels like a business.',
    resultNote: 'Steady ~$17–21k/mo',
    initials: 'V',
    avatarHue: 280,
  },
  {
    id: 'maria',
    name: 'Maria',
    meta: 'Creator · 4 mo. with OFM',
    dateLabel: '5 days ago',
    rating: 5,
    tags: ['Privacy'],
    helpfulCount: 6,
    text: 'Anonymity is critical for me. They documented access levels, who sees what, what can\'t be posted without my approval. Content advice is specific, not a PDF template. Fourth month working together — still here.',
    resultNote: '~$22–25k/mo after launching with the team',
    initials: 'M',
    avatarHue: 160,
  },
  {
    id: 'elena',
    name: 'Elena',
    meta: 'No-face · 7 mo. with OFM',
    dateLabel: '4 days ago',
    rating: 5,
    tags: ['No-face', 'Marketing'],
    text: 'I run a faceless page — worried promo would be harder. They helped with positioning and the funnel based on style, not face. Agency handles chats, I only do shoots. Works well for no-face.',
    initials: 'E',
    avatarHue: 210,
  },
];
