import type { ModelReview } from './types';

export const MODEL_REVIEWS: ModelReview[] = [
  {
    id: 'kristina',
    name: 'Kristina',
    meta: 'Cambió de agencia',
    rating: 5,
    featured: true,
    tags: ['Manager', 'Apoyo'],
    initials: 'K',
    avatarHue: 195,
    text: 'Quiero hablar del trabajo de la manager Yulia — una persona muy atenta, dulce y amable, se toma su trabajo con responsabilidad, ¡una verdadera profesional! Al principio tuve una mala experiencia con otra agencia, no entraré en detalles. Yulia me ayudó a resolver los problemas que surgieron, y los superamos gracias a ella. Me encontró un nuevo equipo, y con ellos empiezo un nuevo capítulo de mi vida — el equipo es buenísimo ❤️ ¡Gracias, Yulia, por tu ayuda y tu apoyo! Todo lo mejor 🥰🙏',
  },
  {
    id: 'alina',
    name: 'Alina',
    meta: 'Empezando con el equipo',
    rating: 5,
    tags: ['Inicio', 'Apoyo'],
    initials: 'A',
    avatarHue: 330,
    text: '¡Hola! Todo genial — me ayudaron con la luz y con un piso para mi primer plan de contenido. El equipo ayuda con las dificultades: si algo no sale, buscan una alternativa o explican cómo hacerlo de otra forma. Así que de momento todo bien, aunque al principio cueste — solo hay que acostumbrarse y coger el ritmo ♥️♥️',
  },
  {
    id: 'karina',
    name: 'Karina',
    meta: '2 semanas en OFM',
    rating: 5,
    tags: ['Adelanto', 'Contenido'],
    initials: 'K',
    avatarHue: 25,
    text: '¡Qué contenta de haber encontrado vuestra agencia! 🌸 ¡Me pagasteis un adelanto ya después del primer contenido! Ayudáis a crear contenido de calidad, sois amables y atentos 💖 Llevamos dos semanas trabajando juntos — ¡y esto es solo el principio! Con vuestra agencia veo futuro y los éxitos que lograremos juntos.',
  },
  {
    id: 'veronika',
    name: 'Verónica',
    meta: 'Lanzó en días',
    rating: 4,
    tags: ['Inicio rápido', 'Honesto'],
    initials: 'V',
    avatarHue: 280,
    text: 'Las chicas son muy amables — te escuchan y eligen la mejor opción; lo importante es no dar vergüenza y hablar de todos tus límites y detalles. Encontraron equipo rápido, en pocos días ya habíamos empezado a trabajar — ¡y la cuenta ya tiene buenos balances! Consejo: confirma cualquier detalle para no acabar en una situación incómoda. Al principio costó entrar en ritmo, pero todo llega con la experiencia 🥺 En resumen, no me arrepiento para nada.',
  },
  {
    id: 'oksana',
    name: 'Oksana',
    meta: 'Enfoque profesional',
    rating: 5,
    tags: ['Profesionalidad'],
    initials: 'O',
    avatarHue: 160,
    text: 'Sinceramente agradecida por la colaboración. Gratamente impresionada por el trabajo y la profesionalidad del personal de la agencia. Se pusieron a trabajar rápido — me sorprendió lo responsable y minucioso que fue todo lo que dependía de ellos, y más aún. Trabajan de forma profesional en cada etapa.',
  },
  {
    id: 'natalia',
    name: 'Natalia',
    meta: 'Transparencia desde el primer día',
    rating: 5,
    tags: ['Confianza', 'Apoyo'],
    initials: 'N',
    avatarHue: 210,
    text: 'Desde el principio de la colaboración sentí confianza en el personal — dieron información clara y honesta sobre la colaboración y las ganancias. Después trabajé con el equipo: me apoyan, me ayudan, dan buenos consejos. Da mucho gusto trabajar con personas que crean tan buen ambiente incluso online.',
  },
];
