import type { ModelReview } from './types';

export const MODEL_REVIEWS: ModelReview[] = [
  {
    id: 'anna',
    name: 'Anna',
    meta: 'Creator · 5 meses con OFM',
    dateLabel: 'Hace 2 meses',
    rating: 5,
    featured: true,
    tags: ['Chats', 'Crecimiento de ingresos'],
    helpfulCount: 14,
    text: 'Siendo honesta: antes de OFM yo misma respondía mensajes hasta altas horas y me quemé al segundo mes. Al unirme, los managers se encargaron del chat y pude dedicarme a las sesiones y al plan de contenido. En cinco meses mis ingresos brutos crecieron unas 4 veces — no digo que le pase a todas, es mi caso. En contra: la primera semana fue de configuración, muchas preguntas por Telegram.',
    resultNote: 'Ahora alrededor de ~$26–30k/mes (varía)',
    initials: 'A',
    avatarHue: 330,
    agencyReply: {
      text: 'Anna, gracias por la reseña sincera — pasamos tu feedback al equipo de chat. Nos alegra que el proceso funcione ahora. Siempre disponibles.',
      dateLabel: 'Hace 2 meses · respuesta OFM',
    },
  },
  {
    id: 'daria',
    name: 'Daria',
    meta: 'Creator · 3 meses con OFM',
    dateLabel: 'Hace 3 semanas',
    rating: 4,
    tags: ['Chats', 'Onboarding'],
    helpfulCount: 8,
    text: 'Puse 4, no 5, a propósito. Buen inicio, manager sensato. En las primeras dos semanas el tono de los mensajes era demasiado comercial — pedí suavizarlo y lo corrigieron en un par de días. Ahora cómoda. El marketing aún está despegando, las cifras suben pero aún no es el resultado final.',
    resultNote: 'Alrededor de $11–13k/mes por ahora',
    initials: 'D',
    avatarHue: 25,
    agencyReply: {
      text: 'Daria, recibido. Ajustamos el tono en DM a tu estilo. Si hace falta — escribe a tu manager directamente, es parte normal del proceso.',
      dateLabel: 'Hace 2 semanas · respuesta OFM',
    },
  },
  {
    id: 'sofia',
    name: 'Sofia',
    meta: 'Creator · 6 meses con OFM',
    dateLabel: 'Hace 1 mes',
    rating: 5,
    tags: ['Desde cero', 'Marketing'],
    helpfulCount: 21,
    text: 'Entré casi desde cero, con miedo a la verificación y a que "no salga bien". Me explicaron paso a paso, sin presión para firmar el día de la solicitud. Reddit + Twitter sí trajeron tráfico, y de noche no atendía chats — dormí bien por primera vez en mucho tiempo. En seis meses mis cifras son otra cosa; antes rondaba los $3k.',
    resultNote: 'Experiencia personal: ~$3k → ahora ~$28–34k/mes',
    initials: 'S',
    avatarHue: 195,
  },
  {
    id: 'victoria',
    name: 'Victoria',
    meta: 'Creator · 8 meses con OFM',
    dateLabel: 'Hace 6 semanas',
    rating: 5,
    tags: ['Marca', 'Contenido'],
    text: 'Para mí no se trataba solo de llevar una página, sino de construir una imagen. Antes probé otros dos equipos — caos. Aquí hay plan, el manager responde en Telegram, informes semanales de cifras. No perfecto, pero por fin se siente como un negocio.',
    resultNote: 'Estable ~$17–21k/mes',
    initials: 'V',
    avatarHue: 280,
  },
  {
    id: 'maria',
    name: 'Maria',
    meta: 'Creator · 4 meses con OFM',
    dateLabel: 'Hace 5 días',
    rating: 5,
    tags: ['Confidencialidad'],
    helpfulCount: 6,
    text: 'El anonimato es clave para mí. Documentaron accesos, quién ve qué, qué no se publica sin mi ok. Consejos de contenido concretos, no una plantilla en PDF. Llevamos cuatro meses — sigo.',
    resultNote: '~$22–25k/mes tras arrancar con el equipo',
    initials: 'M',
    avatarHue: 160,
  },
  {
    id: 'elena',
    name: 'Elena',
    meta: 'No-face · 7 meses con OFM',
    dateLabel: 'Hace 4 días',
    rating: 5,
    tags: ['No-face', 'Marketing'],
    text: 'Llevo página sin rostro — temía que el promo fuera más difícil. Ayudaron con posicionamiento y embudo por estilo, no por cara. Chats en la agencia, yo solo grabo. Me funcionó para no-face.',
    initials: 'E',
    avatarHue: 210,
  },
];
